<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2014-2015 Linagora
 
 This program/library is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published by
 the Free Software Foundation, either version 2.1 of the License, or (at your
 option) any later version.
 
 This program/library is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 for more details.
 
 You should have received a copy of the GNU Lesser General Public License
 along with this program/library; If not, see <http://www.gnu.org/licenses/>
 for the GNU Lesser General Public License version 2.1.
-->
<wsdl:definitions name="demandeDeCongesService"
   targetNamespace="http://petals.ow2.org/se/activiti/unit-test/parser"
   xmlns:tns="http://petals.ow2.org/se/activiti/unit-test/parser" xmlns:bpmn="http://petals.ow2.org/se/bpmn/annotations/1.0"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

   <wsdl:import location="abstract-import.wsdl" namespace="http://petals.ow2.org/se/activiti/unit-test/parser" />

   <!-- ======================== BINDINGS ======================================= -->
   <wsdl:binding name="demandeDeCongesBinding" type="tns:demandeDeConges">
      <soap:binding style="document"
         transport="http://schemas.xmlsoap.org/soap/http" />
      <wsdl:operation name="demanderConges">
         <soap:operation
            soapAction="http://petals.ow2.org/se/Acitivibpmn/1.0/su/demanderConges" />
         <bpmn:operation processDefinitionId="vacationRequest"
            action="startEvent" actionId="request" />
         <bpmn:userId>/*[local-name()='demande']/*[local-name()='demandeur']</bpmn:userId>
         <bpmn:variable name="numberOfDays">
            /*[local-name()='demande']/*[local-name()='nbJourDde']
         </bpmn:variable>
         <bpmn:variable name="startDate">
            /*[local-name()='demande']/*[local-name()='DateDebutDde']
         </bpmn:variable>
         <bpmn:variable name="vacationMotivation">
            /*[local-name()='demande']/*[local-name()='motifDde']
         </bpmn:variable>
         <bpmn:output>valid.xsl</bpmn:output>
         <wsdl:input>
            <soap:body use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal" />
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="validerDemande">
         <soap:operation
            soapAction="http://petals.ow2.org/se/Activitibpmn/1.0/handleRequest" />
         <bpmn:operation processDefinitionId="vacationRequest"
            action="userTask" actionId="handleRequest" />
         <bpmn:processInstanceId>/*[local-name()='validation']/*[local-name()='numeroDde']</bpmn:processInstanceId>
         <bpmn:userId>/*[local-name()='validation']/*[local-name()='valideur']</bpmn:userId>
         <bpmn:variable name="vacationApproved">
            /*[local-name()='validation']/*[local-name()='approbation']
         </bpmn:variable>
         <bpmn:variable name="managerMotivation">
            /*[local-name()='validation']/*[local-name()='motifRefus']
         </bpmn:variable>
         <bpmn:output>valid.xsl</bpmn:output>
         <wsdl:input>
            <soap:body use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal" />
         </wsdl:output>
         <wsdl:fault name="demandeDejaValidee">
            <bpmn:fault name="TaskCompletedException">valid.xsl</bpmn:fault>
            <soap:fault name="demandeDejaValidee" use="literal" />
         </wsdl:fault>
      </wsdl:operation>
      <wsdl:operation name="ajusterDemande">
         <soap:operation
            soapAction="http://petals.ow2.org/se/Activitibpmn/1.0/adjustVacationRequestTask" />
         <bpmn:operation processDefinitionId="vacationRequest"
            action="userTask" actionId="adjustVacationRequestTask" />
         <bpmn:processInstanceId>/*[local-name()='ajustement']/*[local-name()='numeroDdeInitiale']</bpmn:processInstanceId>
         <bpmn:userId>/*[local-name()='ajustement']/*[local-name()='demandeur']</bpmn:userId>
         <bpmn:variable name="numberOfDays">
            /*[local-name()='ajustement']/*[local-name()='nbJourNouvelleDde']
         </bpmn:variable>
         <bpmn:variable name="startDate">
            /*[local-name()='ajustement']/*[local-name()='DateDebutNouvelleDde']
         </bpmn:variable>
         <bpmn:variable name="vacationMotivation">
            /*[local-name()='ajustement']/*[local-name()='motifNouvelleDde']
         </bpmn:variable>
         <bpmn:variable name="resendRequest">
            /*[local-name()='ajustement']/*[local-name()='soumettreModif']
         </bpmn:variable>
         <bpmn:output>valid.xsl</bpmn:output>
         <wsdl:input>
            <soap:body use="literal" />
         </wsdl:input>
         <wsdl:output>
            <soap:body use="literal" />
         </wsdl:output>
         <wsdl:fault name="demandeDejaValidee">
            <bpmn:fault name="TaskCompletedException">valid.xsl</bpmn:fault>
            <soap:fault name="demandeDejaValidee" use="literal" />
         </wsdl:fault>
      </wsdl:operation>
   </wsdl:binding>
   <!-- ======================== SERVICE (SU jbi.xml service-name) ============== -->
   <wsdl:service name="demandeDeCongesService">
      <wsdl:port name="autogenerate" binding="tns:demandeDeCongesBinding">
         <soap:address location="http://localhost:9003/demandeDeConges" />
      </wsdl:port>
   </wsdl:service>

</wsdl:definitions>
